export const refs = {
  day: document.querySelector('.page-main__day-title'),
  date: document.querySelector('.page-main__day-of-month'),
  city: document.querySelector('.page-main__location-now'),
  currentTemp: document.querySelector('.page-main__degree'),
  currentStutusWth: document.querySelector('.page-main__status-weather'),
  feelslike: document.querySelector('.list-decs__info--cld'),
  humidity: document.querySelector('.list-decs__info--hum'),
  wind: document.querySelector('.list-decs__info--wind'),
  divPageMain: document.querySelector('.page-main'),
  img: document.querySelector('.img-current'),
  btn: document.querySelector('.btn-search'),
  input: document.querySelector('.page-second__btn-search'),
  imgCurrentMini: document.querySelectorAll('.img-current-mini'),
  svgCurIc: document.querySelector('.svg-cur-ic'),
  currentDaymini: document.querySelectorAll('.list-info__day'),
  currentDegree: document.querySelectorAll('.list-info__degree'),
  list: document.querySelectorAll('.list-info__item'),
  btnArrow: document.querySelector('.btn-arrow'),
};

export const dayArr = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
];
